---
title: "CPDS with Python"
description-meta: "CPDS with Python - Course Materials"
---

**Course Code:** MA26003 & MA26005

**Academic Year:** 2026–2027

**Department:** Mathematics

**Institution:** National Institute of Technology Warangal

---

### Lecture Notes

| Material | Link |
|---|---|
| Lecture Notes | [📄 View Notes PDF](course_notes.pdf){target="_blank"} |

### Python codes created during class

| Class | Material | Download |
|---|---|---|
| Class 1 | [View Class 1 Notebook](class_codes/class 1.ipynb) | [⬇️ Download](class_codes/class 1.ipynb) |
| Class 2 | [View Class 2 Notebook](class_codes/class 2.ipynb) | [⬇️ Download](class_codes/class 2.ipynb) |
| Class 3 | [View Class 3 Notebook](class_codes/class 3.ipynb) | [⬇️ Download](class_codes/class 3.ipynb) |
| Class 4 | [View Class 4 Notebook](class_codes/class_4.ipynb) | [⬇️ Download](class_codes/class_4.ipynb) |
| Class 5 | [View Class 5 Notebook](class_codes/class_5.ipynb) | [⬇️ Download](class_codes/class_5.ipynb) |
| Class 6 | [View Class 6 Notebook](class_codes/class_6.ipynb) | [⬇️ Download](class_codes/class_6.ipynb) |
| Class 7 | [View Class 7 Notebook](class_codes/class_7.ipynb) | [⬇️ Download](class_codes/class_7.ipynb) |
| Class 8 | [View Class 8 Notebook](class_codes/class_8.ipynb) | [⬇️ Download](class_codes/class_8.ipynb) |
| Class 9,10,11 | [View Class 9,10,11 Notebook](class_codes/Class_9_10_11_Introduction_to_Packages_and_NumPy.ipynb) | [⬇️ Download](class_codes/Class_9_10_11_Introduction_to_Packages_and_NumPy.ipynb) |

## Lab Classes

| Class | Material | Download |
|---|---|---|
| Lab Class 1 | [View Lab Class 1 Notebook](class_codes/Lab-Class-1.ipynb) | [⬇️ Download](class_codes/Lab-Class-1.ipynb) |
| Lab Class 2 | [View Lab Class 2 Notebook](class_codes/Lab_Class_2.ipynb) | [⬇️ Download](class_codes/Lab_Class_2.ipynb) |
| Lab Class 3 | [View Lab Class 3 Notebook](class_codes/Lab_Class_3.ipynb) | [⬇️ Download](class_codes/Lab_Class_3.ipynb) |

## Assignments

available soon